super_noel:
    resource: "@SuperNoelBundle/Controller/"
    type:     annotation
    prefix:   /
app:
    resource: '@AppBundle/Controller/'
    type: annotation
enfant_route:
    path: /enfant/{childId}
    defaults: { _controller: SuperNoelBundle:Home:gift }