<?php

namespace SuperNoelBundle\Repository;

/**
 * GiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getUntreated()
//    {
//        // Exemple
//        $persister = $this->_em->getUnitOfWork()->getEntityPersister($this->_entityName);
//        return $persister->loadAll($criteria, $orderBy, $limit, $offset);
//    }
}
